# Generated by Django 2.1.7 on 2019-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note1', models.CharField(max_length=255)),
                ('note2', models.CharField(blank=True, max_length=255, null=True)),
                ('note3', models.CharField(blank=True, max_length=255, null=True)),
                ('note4', models.CharField(blank=True, max_length=255, null=True)),
                ('isdead', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='proxyip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('isdead', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('isuse', models.CharField(max_length=255)),
                ('isdead', models.CharField(max_length=254)),
                ('utk', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('nutk', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='wxname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxname1', models.CharField(max_length=255)),
                ('wxname2', models.CharField(blank=True, max_length=255, null=True)),
                ('wxname3', models.CharField(blank=True, max_length=255, null=True)),
                ('wxname4', models.CharField(blank=True, max_length=255, null=True)),
                ('isdead', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
