# Generated by Django 2.2.1 on 2019-10-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footballwealthresolution',
            options={'ordering': ('-create_time',), 'verbose_name': '足球财富推荐解析', 'verbose_name_plural': '足球财富推荐解析'},
        ),
    ]
