# Generated by Django 2.2.1 on 2019-10-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolmodel', '0002_auto_20191021_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(verbose_name='手机号'),
        ),
    ]
