# Generated by Django 2.1.7 on 2019-04-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0002_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
