# Generated by Django 2.1.7 on 2019-05-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0003_remove_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='rid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=255)),
                ('home', models.CharField(max_length=255)),
                ('guest', models.CharField(max_length=255)),
                ('chatCount', models.CharField(max_length=255)),
                ('displayState', models.CharField(max_length=255)),
                ('isdead', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
