# Generated by Django 2.1.7 on 2019-05-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0004_rid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rid',
            name='displayState',
        ),
    ]
