# Generated by Django 2.1.7 on 2019-05-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0005_remove_rid_displaystate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rid',
            name='id',
        ),
        migrations.AlterField(
            model_name='rid',
            name='rid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
