# Generated by Django 2.1.7 on 2019-05-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0006_auto_20190507_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxname',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
