# Generated by Django 2.1.7 on 2019-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0007_wxname_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxyip',
            name='ip',
        ),
        migrations.AddField(
            model_name='proxyip',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proxyip',
            name='proxy_http_http',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxyip',
            name='port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
