# Generated by Django 2.1.7 on 2019-05-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0008_auto_20190508_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyip',
            name='hiding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
