# Generated by Django 2.1.7 on 2019-05-09 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0009_proxyip_hiding'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_voice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_title', models.CharField(max_length=255, verbose_name='房间ID')),
                ('log_data', models.CharField(max_length=255, verbose_name='日志数据')),
                ('log_time', models.CharField(max_length=255, verbose_name='日志生成时间')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'verbose_name': '唯彩会喊话器日志',
                'verbose_name_plural': '唯彩会喊话器日志',
            },
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': '广告语', 'verbose_name_plural': '广告语'},
        ),
        migrations.AlterModelOptions(
            name='rid',
            options={'verbose_name': '唯彩会直播间列表', 'verbose_name_plural': '唯彩会直播间列表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '唯彩账号', 'verbose_name_plural': '唯彩账号'},
        ),
        migrations.AddField(
            model_name='note',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AddField(
            model_name='note',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
        migrations.AddField(
            model_name='proxyip',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AddField(
            model_name='proxyip',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
        migrations.AddField(
            model_name='rid',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AddField(
            model_name='rid',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
        migrations.AddField(
            model_name='wxname',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
        migrations.AddField(
            model_name='wxname',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
        migrations.AlterField(
            model_name='note',
            name='isdead',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='已被封，默认不填'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note1',
            field=models.CharField(max_length=255, verbose_name='广告语1'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='广告语2'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='广告语3'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='广告语4'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='填写者'),
        ),
        migrations.AlterField(
            model_name='rid',
            name='chatCount',
            field=models.CharField(max_length=255, verbose_name='房间人数'),
        ),
        migrations.AlterField(
            model_name='rid',
            name='guest',
            field=models.CharField(max_length=255, verbose_name='客队'),
        ),
        migrations.AlterField(
            model_name='rid',
            name='home',
            field=models.CharField(max_length=255, verbose_name='主队'),
        ),
        migrations.AlterField(
            model_name='rid',
            name='isdead',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='已经结束'),
        ),
        migrations.AlterField(
            model_name='rid',
            name='rid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='房间ID'),
        ),
    ]
