# Generated by Django 2.2.1 on 2019-05-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0011_remove_log_voice_log_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyip',
            options={'verbose_name': '代理IP', 'verbose_name_plural': '代理IP'},
        ),
        migrations.AlterModelOptions(
            name='wxname',
            options={'verbose_name': '微信', 'verbose_name_plural': '微信'},
        ),
        migrations.AlterField(
            model_name='log_voice',
            name='log_title',
            field=models.CharField(max_length=255, verbose_name='日志类型'),
        ),
    ]
