# Generated by Django 2.2.1 on 2019-06-04 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0012_auto_20190519_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='bifen_mofang',
            fields=[
                ('match_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='比赛ID')),
                ('name_league', models.CharField(blank=True, max_length=255, null=True, verbose_name='联赛名称')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='比赛时间')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='比赛状态')),
                ('home_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='主队名称')),
                ('home_ranking', models.CharField(blank=True, max_length=255, null=True, verbose_name='主队排名')),
                ('matchhomescore', models.CharField(blank=True, max_length=255, null=True, verbose_name='主队得分')),
                ('away_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='客队名称')),
                ('away_ranking', models.CharField(blank=True, max_length=255, null=True, verbose_name='客队排名')),
                ('matchawayscore', models.CharField(blank=True, max_length=255, null=True, verbose_name='客队得分')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='cookies_hiyuncai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies', models.CharField(max_length=255, verbose_name='cookies')),
            ],
        ),
    ]
