# Generated by Django 2.2.1 on 2019-06-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0013_bifen_mofang_cookies_hiyuncai'),
    ]

    operations = [
        migrations.CreateModel(
            name='zuqiumofang_user',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='作者ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者名称')),
                ('has_game', models.CharField(blank=True, max_length=255, null=True, verbose_name='？？')),
                ('is_author', models.CharField(blank=True, max_length=255, null=True, verbose_name='？？')),
                ('is_follow', models.CharField(blank=True, max_length=255, null=True, verbose_name='是否关注')),
                ('poster', models.CharField(blank=True, max_length=255, null=True, verbose_name='？？')),
                ('rc', models.CharField(blank=True, max_length=255, null=True, verbose_name='红')),
                ('wc', models.CharField(blank=True, max_length=255, null=True, verbose_name='走')),
                ('bc', models.CharField(blank=True, max_length=255, null=True, verbose_name='黑')),
                ('rr', models.CharField(blank=True, max_length=255, null=True, verbose_name='周返还率')),
                ('sr', models.CharField(blank=True, max_length=255, null=True, verbose_name='周胜率')),
                ('vote_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='票数')),
            ],
            options={
                'verbose_name': '足球财富排行榜',
                'verbose_name_plural': '足球财富排行榜',
            },
        ),
        migrations.AlterModelOptions(
            name='bifen_mofang',
            options={'verbose_name': '足球魔方比分数据', 'verbose_name_plural': '足球魔方比分数据'},
        ),
    ]
