# Generated by Django 2.2.1 on 2019-06-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0015_auto_20190606_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='zuqiumofang_post',
            fields=[
                ('post_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='推荐ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者名称')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐正文')),
                ('create_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '足球魔方推荐',
                'verbose_name_plural': '足球魔方推荐',
            },
        ),
    ]
