# Generated by Django 2.2.1 on 2019-06-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0016_zuqiumofang_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuqiumofang_post',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='推荐正文'),
        ),
    ]
