# Generated by Django 2.2.1 on 2019-06-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0017_auto_20190606_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuqiumofang_post',
            name='strandlist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐单'),
        ),
    ]
