# Generated by Django 2.2.1 on 2019-06-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0018_zuqiumofang_post_strandlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuqiumofang_post',
            name='strandlist',
            field=models.TextField(blank=True, null=True, verbose_name='推荐单'),
        ),
    ]
