# Generated by Django 2.2.1 on 2019-06-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0019_auto_20190607_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuqiumofang_user',
            name='rangking',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='排名'),
        ),
    ]
