# Generated by Django 2.2.1 on 2019-06-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0020_zuqiumofang_user_rangking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zuqiumofang_user',
            old_name='rangking',
            new_name='ranking',
        ),
    ]
