# Generated by Django 2.2.1 on 2019-06-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0021_auto_20190607_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuqiumofang_post',
            name='ranking',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='排名'),
        ),
    ]
