# Generated by Django 2.2.1 on 2019-06-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0022_zuqiumofang_post_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='zuqiumofang_tuijian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者ID')),
                ('tuijian_data', models.TextField(blank=True, null=True, verbose_name='推荐正文')),
            ],
            options={
                'verbose_name': '推荐',
                'verbose_name_plural': '推荐',
            },
        ),
    ]
