# Generated by Django 2.2.1 on 2019-06-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0023_zuqiumofang_tuijian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zuqiumofang_tuijian',
            name='tuijian_data',
        ),
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='ID_bet007',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='比赛ID'),
        ),
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='away',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客队'),
        ),
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='create_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐时间'),
        ),
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='home',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='主队'),
        ),
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='match_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='比赛ID'),
        ),
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='tuijian',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='玩法列表'),
        ),
    ]
