# Generated by Django 2.2.1 on 2019-06-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0024_auto_20190608_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='bc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='黑'),
        ),
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='ranking',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='排名'),
        ),
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='rc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='红'),
        ),
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='wc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='走'),
        ),
    ]
