# Generated by Django 2.2.1 on 2019-06-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0025_auto_20190608_0526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zuqiumofang_post',
            options={'verbose_name': '足球财富文章列表', 'verbose_name_plural': '足球财富文章列表'},
        ),
        migrations.AlterModelOptions(
            name='zuqiumofang_tuijian',
            options={'verbose_name': '足球财富推荐', 'verbose_name_plural': '足球财富推荐'},
        ),
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='tongji',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐'),
        ),
    ]
