# Generated by Django 2.2.1 on 2019-06-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0026_auto_20190609_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuqiumofang_user',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='昵称'),
        ),
    ]
