# Generated by Django 2.2.1 on 2019-06-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0027_zuqiumofang_user_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zuqiumofang_user',
            options={'ordering': ('ranking',), 'verbose_name': '足球财富排行榜', 'verbose_name_plural': '足球财富排行榜'},
        ),
        migrations.AlterField(
            model_name='zuqiumofang_post',
            name='create_time',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='创建时间'),
        ),
    ]
