# Generated by Django 2.2.1 on 2019-06-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0031_auto_20190614_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuqiumofang_post',
            name='create_time',
            field=models.DateTimeField(blank=True, max_length=255, null=True, verbose_name='创建时间'),
        ),
    ]
