# Generated by Django 2.2.1 on 2019-06-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0032_auto_20190614_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='tuijian_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='推荐ID'),
        ),
        migrations.AlterField(
            model_name='zuqiumofang_tuijian',
            name='post_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文章ID'),
        ),
    ]
