# Generated by Django 2.2.1 on 2019-06-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0034_auto_20190614_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zuqiumofang_tuijian',
            name='tuijian_id',
        ),
        migrations.AlterField(
            model_name='zuqiumofang_tuijian',
            name='id',
            field=models.IntegerField(max_length=255, primary_key=True, serialize=False, verbose_name='推荐ID'),
        ),
    ]
