# Generated by Django 2.2.1 on 2019-06-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0035_auto_20190614_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuqiumofang_tuijian',
            name='tuijian',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='玩法列表'),
        ),
    ]
