# Generated by Django 2.2.1 on 2019-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0036_auto_20190614_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作者昵称'),
        ),
    ]
