# Generated by Django 2.2.1 on 2019-06-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0037_zuqiumofang_tuijian_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuqiumofang_tuijian',
            name='create_time',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name='推荐时间'),
        ),
    ]
