# Generated by Django 2.2.1 on 2019-06-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0039_auto_20190615_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuqiumofang_tuijian',
            name='create_time',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='推荐时间'),
        ),
    ]
