# Generated by Django 2.2.1 on 2019-06-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolModel', '0041_auto_20190615_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuqiumofang_tuijian',
            name='state',
            field=models.IntegerField(blank=True, null=True, verbose_name='结果'),
        ),
    ]
